// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZDiIrKuOv8L_bo2v4wbZpF90aeaLI8KM',
    appId: '1:872154204208:web:b89573f516f3360d2685f5',
    messagingSenderId: '872154204208',
    projectId: 'quickbites-67c25',
    authDomain: 'quickbites-67c25.firebaseapp.com',
    storageBucket: 'quickbites-67c25.firebasestorage.app',
    measurementId: 'G-1FY4Q46BS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuzo813z3kzvMpLBMfH8LdrDjkW8_TvEU',
    appId: '1:872154204208:android:7f3e59e6e2499c7d2685f5',
    messagingSenderId: '872154204208',
    projectId: 'quickbites-67c25',
    storageBucket: 'quickbites-67c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAod1sZfy3wmru1-kH6mmshp8MEMfenw_Y',
    appId: '1:872154204208:ios:ec854562845d80512685f5',
    messagingSenderId: '872154204208',
    projectId: 'quickbites-67c25',
    storageBucket: 'quickbites-67c25.firebasestorage.app',
    iosBundleId: 'com.example.quickbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAod1sZfy3wmru1-kH6mmshp8MEMfenw_Y',
    appId: '1:872154204208:ios:ec854562845d80512685f5',
    messagingSenderId: '872154204208',
    projectId: 'quickbites-67c25',
    storageBucket: 'quickbites-67c25.firebasestorage.app',
    iosBundleId: 'com.example.quickbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZDiIrKuOv8L_bo2v4wbZpF90aeaLI8KM',
    appId: '1:872154204208:web:8c573b575b7596b52685f5',
    messagingSenderId: '872154204208',
    projectId: 'quickbites-67c25',
    authDomain: 'quickbites-67c25.firebaseapp.com',
    storageBucket: 'quickbites-67c25.firebasestorage.app',
    measurementId: 'G-NFYWXDLP2G',
  );
}
